setwd('C:\\Users\\maxim\\Desktop\\code\\hammer\\infil\\curated_data\\pure_samples\\iris')
library(affy)
list.celfiles()
data <- ReadAffy()
eset <- rma(data)
write.exprs(eset, file="log_normalized_expression_mat.txt")
library('hug133a.db')
library('hgu133a.db')
Annot <- data.frame(ACCNUM=sapply(contents(hgu133aACCNUM), paste, collapse=", "), SYMBOL=sapply(contents(hgu133aSYMBOL), paste, collapse=", "), DESC=sapply(contents(hgu133aGENENAME), paste, collapse=", "))
my_frame <- data.frame(exprs(eset))
head(my_frame)
all <- merge(Annot, my_frame, by.x=0, by.y=0, all=T)
head(all)
head(Annot)
write.table(all, file="data.ann.tsv", sep="\t")